### ISSUE TITLE
Type order problem

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/uniontypes#1]
Wow, such a useful lib! 
It's a great pleasure and honor to file the first issue... :-)

There seems to be a problem with the type ordering - the types are not fully commutative, it seems.
In the example below, `Union<SomeClass, AType>` works fine, but `Union<AType, SomeClass>` gives the following compilation error:
```
C:\HaxeToolkit\haxe\std/haxe/macro/MacroStringTools.hx:70: characters 84-89 : AType is not a value
C:\HaxeToolkit\haxe\std/haxe/macro/MacroStringTools.hx:70: characters 84-89 : For function argument 't'
src/Main.hx:6: characters 20-43 : Defined in this class
src/Main.hx:6: characters 20-43 : Void should be ATypeOrSomeClassType
```
I'm on Haxe 4.2.0-rc.1+9a75d9d2e if that matters.

```
import Union;

class Main {
	static function main() {
		// works fine:
		final worksFine:Union<SomeClass, AType> = {name: 'Bob'};
		
		// problem here, when the order of the types is reversed:
		final doesntWork:Union<AType, SomeClass> = {name: 'Bob'};
	}
}

typedef AType = {
	final name:String;
}

class SomeClass {
	public final s:String;

	public function new(s)
		this.s = s;
}
```

**Comment by ciscoheat** [comment]
The pleasure is all mine... almost, because this was a tricky one. :) It was quite confusing until it was all clear. A `typedef` can be an alias for a type, but the underlying type was, in this case, an anonymous type. Which you can't check at runtime, since an actual type like a class is not created for it. Hence the cryptic error message which was really `Std.isOfType` looking for a non-existing type definition.

For anonymous types, the check is now made towards any non-optional fields, but sorted last in the union order to avoid that more expensive check.

**Comment by cambiata** [comment]
Thanks!
